name: test
on: push
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tox
        run: |
          uv tool install tox --with tox-uv
          tox run
